#!/usr/bin/env python3
"""
PR Integration - Bridge between gate receipt and GitHub PR workflow.

This script:
1. Creates a PR from the execution changes (if not already done)
2. Creates a human review record linked to the PR
3. Sets up the pending_review state machine

Usage:
    # After gate completes with pending_promote decision:
    python pr_integration.py --gate-receipt /path/to/gate-receipt.json --repo lanyasheng/auto-improvement-orchestrator-skill
    
    # Or with existing PR:
    python pr_integration.py --gate-receipt /path/to/gate-receipt.json --repo lanyasheng/auto-improvement-orchestrator-skill --pr-number 1
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Tuple

from pr_state import PRStateManager, ReviewRecord


def run_gh_command(args: list, repo: Optional[str] = None, check: bool = True) -> Tuple[str, str, int]:
    """Run a gh CLI command and return (stdout, stderr, returncode)."""
    cmd = ["gh"]
    if repo:
        cmd.extend(["-R", repo])
    cmd.extend(args)
    result = subprocess.run(cmd, capture_output=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"gh command failed: {result.stderr}")
    return result.stdout, result.stderr, result.returncode


def create_pr(repo: str, title: str, body: str, base: str = "main", head: Optional[str] = None) -> int:
    """Create a PR and return the PR number."""
    cmd_args = ["pr", "create", "--title", title, "--body", body, "--base", base]
    if head:
        cmd_args.extend(["--head", head])
    output, _, _ = run_gh_command(cmd_args, repo)
    # Parse PR number from output (format: https://github.com/owner/repo/pull/123)
    for line in output.split("\n"):
        if "/pull/" in line:
            pr_number = int(line.split("/pull/")[-1].strip())
            return pr_number
    raise RuntimeError(f"Could not parse PR number from output: {output}")


def get_current_branch() -> str:
    """Get current git branch."""
    result = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"git command failed: {result.stderr}")
    return result.stdout.strip()


def load_gate_receipt(path: str) -> dict:
    """Load gate receipt JSON."""
    with open(Path(path).expanduser().resolve(), "r") as f:
        return json.load(f)


def format_pr_body(gate_receipt: dict, run_id: str, candidate_id: str) -> str:
    """Format PR body with context from gate receipt."""
    decision = gate_receipt.get("decision", "unknown")
    reason = gate_receipt.get("reason", "No reason provided")
    candidate_category = gate_receipt.get("candidate_category", "unknown")

    body = f"""## Auto-Improvement Candidate

**Run ID**: `{run_id}`  
**Candidate ID**: `{candidate_id}`  
**Gate Decision**: `{decision}`  
**Category**: `{candidate_category}`

### Gate Reasoning

> {reason}

---

### Human Review Required

This candidate requires human review before promotion.

**Review Instructions**:
1. Review the changes in this PR
2. Leave a comment with your decision:
   - `/approve` or `LGTM` to approve
   - `/reject` to reject
   - `/hold` or `needs changes` to request modifications
3. Or add labels: `approved`, `rejected`, `pending-review`

---

### State Machine

- Current state: `pending_review`
- Next state: `approved` | `rejected`

---

*Generated by auto-improvement-orchestrator human review integration*
"""
    return body


def main() -> int:
    parser = argparse.ArgumentParser(description="PR Integration - Create PR and human review record")
    parser.add_argument("--gate-receipt", required=True, help="Path to gate receipt JSON")
    parser.add_argument("--repo", required=True, help="GitHub repo (owner/repo)")
    parser.add_argument("--pr-number", type=int, help="Existing PR number (optional, skips PR creation)")
    parser.add_argument("--state-root", default="/Users/study/.openclaw/shared-context/intel/auto-improvement/generic-skill")
    parser.add_argument("--dry-run", action="store_true", help="Don't create PR, just show what would be done")
    args = parser.parse_args()

    state_root = Path(args.state_root).expanduser().resolve()
    manager = PRStateManager(state_root)

    # Load gate receipt
    gate_receipt = load_gate_receipt(args.gate_receipt)
    run_id = gate_receipt.get("run_id", "")
    candidate_id = gate_receipt.get("candidate_id", "")

    if not run_id or not candidate_id:
        print("Error: Gate receipt missing run_id or candidate_id")
        return 1

    print(f"Gate receipt loaded:")
    print(f"  Run ID: {run_id}")
    print(f"  Candidate ID: {candidate_id}")
    print(f"  Decision: {gate_receipt.get('decision')}")

    # Determine PR number
    pr_number = args.pr_number
    pr_url = ""

    if pr_number:
        print(f"\nUsing existing PR #{pr_number}")
        pr_url = f"https://github.com/{args.repo}/pull/{pr_number}"
    else:
        # Create new PR
        print(f"\nCreating new PR...")
        
        if args.dry_run:
            print("[DRY RUN] Would create PR")
            return 0

        # Get current branch
        try:
            head_branch = get_current_branch()
        except RuntimeError as e:
            print(f"Warning: Could not get current branch: {e}")
            head_branch = None

        # Format PR title and body
        candidate_category = gate_receipt.get("candidate_category", "candidate")
        title = f"[Auto-Improvement] {candidate_category} - {run_id}/{candidate_id}"
        body = format_pr_body(gate_receipt, run_id, candidate_id)

        try:
            pr_number = create_pr(args.repo, title, body, head=head_branch)
            pr_url = f"https://github.com/{args.repo}/pull/{pr_number}"
            print(f"✓ PR created: #{pr_number}")
        except RuntimeError as e:
            print(f"✗ Failed to create PR: {e}")
            print("\nTip: Make sure you have uncommitted changes or a feature branch")
            return 1

    # Create human review record
    print(f"\nCreating human review record...")
    record = manager.create_review(
        run_id=run_id,
        candidate_id=candidate_id,
        pr_number=pr_number,
        pr_url=pr_url,
        gate_receipt_path=args.gate_receipt
    )

    print(f"✓ Review record created:")
    print(f"  State: {record.state}")
    print(f"  PR: #{pr_number}")
    print(f"  Receipt: {manager._review_path(run_id, candidate_id)}")

    # Post initial review comment
    print(f"\nPosting initial review comment to PR #{pr_number}...")
    from pr_review_writeback import format_receipt_comment
    comment_body = format_receipt_comment(record, gate_receipt)
    
    try:
        from pr_review_writeback import post_comment
        post_comment(args.repo, pr_number, comment_body)
        print("✓ Initial comment posted")
    except RuntimeError as e:
        print(f"Warning: Could not post comment: {e}")

    print(f"\n---")
    print(f"Human review integration complete!")
    print(f"PR: {pr_url}")
    print(f"State: pending_review → waiting for human decision")
    print(f"\nNext steps:")
    print(f"  1. Human reviewer leaves /approve or /reject comment on PR")
    print(f"  2. Run: python pr_review_trigger.py --repo {args.repo} --pr-number {pr_number} --run-id {run_id} --candidate-id {candidate_id}")
    print(f"  3. Review state updates to approved/rejected")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
