#!/usr/bin/env python3
"""
PR Review Writeback - Write human review receipt as PR comment.

This script posts the human review receipt (decision artifact) as a comment
on the associated GitHub PR, providing an audit trail.

Usage:
    python pr_review_writeback.py --repo lanyasheng/auto-improvement-orchestrator-skill --run-id run-xxx --candidate-id cand-xxx
"""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from pr_state import PRStateManager, ReviewRecord


def run_gh_command(args: list, repo: Optional[str] = None) -> str:
    """Run a gh CLI command and return output."""
    cmd = ["gh"]
    if repo:
        cmd.extend(["-R", repo])
    cmd.extend(args)
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"gh command failed: {result.stderr}")
    return result.stdout


def post_comment(repo: str, pr_number: int, body: str) -> str:
    """Post a comment to a PR and return the comment URL."""
    output = run_gh_command(["pr", "comment", str(pr_number), "--body", body], repo)
    return output.strip()


def format_receipt_comment(record: ReviewRecord, gate_receipt: Optional[dict] = None) -> str:
    """Format a human review receipt as a Markdown comment."""
    status_emoji = {
        "pending_review": "⏳",
        "reviewed": "👀",
        "approved": "✅",
        "rejected": "❌",
    }.get(record.state, "📋")

    comment = f"""{status_emoji} **Human Review Receipt**

| Field | Value |
|-------|-------|
| **Run ID** | `{record.run_id}` |
| **Candidate ID** | `{record.candidate_id}` |
| **State** | `{record.state}` |
| **Decision** | `{record.decision or "pending"}` |
| **Decision Source** | `{record.decision_source or "n/a"}` |
| **Reviewer** | `{record.reviewer or "n/a"}` |
| **PR** | #{record.pr_number} |
| **Created** | `{record.created_at}` |
| **Updated** | `{record.updated_at}` |
"""

    if record.gate_receipt_path:
        comment += f"\n**Gate Receipt**: `{record.gate_receipt_path}`\n"

    if gate_receipt:
        gate_decision = gate_receipt.get("decision", "unknown")
        comment += f"\n**Gate Decision**: `{gate_decision}`\n"
        if gate_receipt.get("reason"):
            comment += f"\n> {gate_receipt.get('reason')}\n"

    comment += f"\n---\n*Generated by auto-improvement-orchestrator human review integration*"

    return comment


def load_gate_receipt(gate_receipt_path: str) -> Optional[dict]:
    """Load gate receipt JSON if available."""
    try:
        path = Path(gate_receipt_path).expanduser().resolve()
        if path.exists():
            with open(path, "r") as f:
                return json.load(f)
    except Exception as e:
        print(f"Warning: Could not load gate receipt: {e}")
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="PR Review Writeback - Post human review receipt to PR")
    parser.add_argument("--repo", required=True, help="GitHub repo (owner/repo)")
    parser.add_argument("--run-id", required=True, help="Run ID from orchestrator")
    parser.add_argument("--candidate-id", required=True, help="Candidate ID")
    parser.add_argument("--state-root", default="/Users/study/.openclaw/shared-context/intel/auto-improvement/generic-skill")
    parser.add_argument("--dry-run", action="store_true", help="Don't post, just show what would be posted")
    parser.add_argument("--update-only", action="store_true", help="Only update if state changed since last post")
    args = parser.parse_args()

    state_root = Path(args.state_root).expanduser().resolve()
    manager = PRStateManager(state_root)

    # Load review record
    record = manager.load_review(args.run_id, args.candidate_id)
    if not record:
        print(f"Error: No review record found for {args.run_id}/{args.candidate_id}")
        return 1

    print(f"Review record loaded:")
    print(f"  State: {record.state}")
    print(f"  Decision: {record.decision or 'pending'}")
    print(f"  PR: #{record.pr_number}")

    # Load gate receipt if available
    gate_receipt = None
    if record.gate_receipt_path:
        gate_receipt = load_gate_receipt(record.gate_receipt_path)

    # Format comment
    comment_body = format_receipt_comment(record, gate_receipt)

    if args.dry_run:
        print("\n--- Comment preview ---")
        print(comment_body)
        print("--- End preview ---")
        return 0

    # Post comment
    print(f"\nPosting receipt to PR #{record.pr_number}...")
    try:
        result = post_comment(args.repo, record.pr_number, comment_body)
        print(f"✓ Comment posted: {result}")
    except RuntimeError as e:
        print(f"✗ Failed to post comment: {e}")
        return 1

    # Update record with receipt path
    record.receipt_path = f"pr:{record.pr_number}:comment"
    manager._save_review(record)

    print(f"\nReceipt path updated: {record.receipt_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
